server:
  port: 10085

spring:
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    publisher-confirm-type: correlated
    #开启ack
    listener:
      simple:
        max-concurrency: 100 #设置最大消费端数
        acknowledge-mode: manual #自动签收auto  手动 manual
        retry:
          enabled: true
          max-attempts: 5 #最大重试3次
          initial-interval: 3000
          multiplier: 2
